### ISSUE TITLE
CheckBox Click Event

### ISSUE THREAD

**Issue by nrossBEng** [unipsycho/LabVIEWdotNetDataGrid#18]
When you click a "Check" column, it does not seem to update until the selected cell is changed. Therefore, the Get DataArray.vi does not read out the updated table after a check/uncheck event. I tested this using the Example Simple DataBinding.vi and placing the Get DataArray.vi outside of the event structure.
![image](https://cloud.githubusercontent.com/assets/20167786/16584537/9f49af44-428a-11e6-9212-028002517547.png)

**Comment by unipsycho** [comment]
nrossBEng, ya this is the case with any cell actually in a datagrid.  you are still editing a cell when you change the text, checkbox, dropdown or anything until you tab out, hit enter, or click out of that cell.  There may be a way to use cell validation against the format of that cell to test for a valid change and fire the event to edit the cell, but this is not the default behavior of a datagrid so not sure how well that would work.

**Comment by unipsycho** [comment]
found a usable solution for this for another project. Detect the cell validation, need to merge back to LV2013 and integrate, this VI is 2016
[CellValidating Event Callback.zip](https://github.com/unipsycho/LabVIEWdotNetDataGrid/files/1341068/CellValidating.Event.Callback.zip)

**Comment by picklecolor2** [comment]
This is a great library. I just found it today and I'm working on integrating it into a project. I think this is the behavior I'm seeing. If I click the drop arrow for a combo and then click on a selection and end my VI I don't see updated data in the table. Not to press your schedule, but is this something I can help with? Would be great to have a fix in the near future.

I tried your attachment and I'm not seeing a change in behavior. I haven't diff'd them, but it looks the same as the one in the current code base.

**Comment by unipsycho** [comment]
Ya would be great if you could help on this issue, seems a little more complex still than I first thought.  The cell change on a checkbox fires the event, but the databound data in the datatable is not updating with that change.  Might be similar issues to the combo selections, since they would likely work the same, as content within the cell of a custom type.  So, need a way to ensure that it updates the datatable on a combo selection change or checkbox change.

**Comment by picklecolor2** [comment]
I have a working solution that implements the suggestion [here](https://stackoverflow.com/questions/5652957/what-event-catches-a-change-of-value-in-a-combobox-in-a-datagridviewcell). There's just an additional callback that if the data is dirty, but hasn't been committed then go ahead and commit the change. I'll test some more this evening. If it looks like it's working correctly I'll try to prep a pull request. I haven't done it across LabVIEW verisons before and I don't have 2013 installed, but I think the change will be limited to a new callback VI and a change to SetupCallBackEvents.vi.
