### ISSUE TITLE
Bug in Data Error Event Callback

### ISSUE THREAD

**Issue by SweathaKrishna** [unipsycho/LabVIEWdotNetDataGrid#19]
Data Error Event callback is not generating Data Error User event. Instead it is sending "UserAddedRow" event. This is because of unbundling the "UserAddedRow" reference.
![callback bug](https://cloud.githubusercontent.com/assets/22887221/19436966/d100bd7c-9490-11e6-81b5-5e3218fb47aa.png)

**Comment by unipsycho** [comment]
thanks sweathaKrishna, I've made the correction at head revision.
