### ISSUE TITLE
Sort Bug

### ISSUE THREAD

**Issue by miketech79** [unipsycho/LabVIEWdotNetDataGrid#23]
If you sort with the different cell example option you can encounter errors. It also seems that there is no way to disable the sort option, either by editing the true constant in the initialize or by placing the property node to set this on the same wire as just before the DataGridView Show method.

**Comment by unipsycho** [comment]
added fix for issue: #23.  The top level grid sort property doesn't work do what I thought, so apparently each column has to have the sort method applied.  I've added this to the column setup, so now the sorting can be turned off (which helps with performance some as well).
