### ISSUE TITLE
Many Items Not In Palettes

### ISSUE THREAD

**Issue by JamesWiresmith** [unipsycho/LabVIEWdotNetDataGrid#24]
When I'm using this there are several items I have to go looking in the vi.lib part of dependencies for e.g. event handler decoding. I would suggest a more complete palette set. Perhaps with easy VIs at the top then sup-palettes for dataview, datagrid and event handling.

**Comment by unipsycho** [comment]
you are right, the palettes are pretty thin, and I did do that on purpose as most users of the grid are not power users, so the simple palette is all I wanted to provide, and any power users can easily use the extra methods in the classes to do more, or even directly with the .net control reference.  I probably won't do this one, as its the first request I've had for it here or the forums, so will just keep it in mind if I get to another major update anytime.
