### ISSUE TITLE
Read Only Per Column

### ISSUE THREAD

**Issue by JamesWiresmith** [unipsycho/LabVIEWdotNetDataGrid#25]
Hi,

I'm looking at using this in an application and need certain columns to be read only. I've pulled the source and see you can do this per table in the latest commits.

Is there a reason to not just add a read only property to the column setup definition? I will be doing this or something similar from my project so can submit it back if desired.

**Comment by unipsycho** [comment]
james, might be a nice feature to add, feel free to submit it back, sure.  I only focused on the basics of the gridview, even though there is far more configurability than what LabVIEW tables offer, so any extra capaibilities is nice to have access to.  I don't think too many people are looking for this feature though, but hey, who knows?
