### ISSUE TITLE
Dependancy to an External Packed Library

### ISSUE THREAD

**Issue by SimonRPSM** [unipsycho/LabVIEWdotNetDataGrid#3]
Greetings, Mike;

Just tried opening the code and there seem to be a few dependencies to a Prolucid library (PLT Common Functions). Is that supposed to be there and, if so, got a link to that library?

Thanks for your work;
Cordially;
SP

**Comment by unipsycho** [comment]
Hey, sorry Simon, I had that cross linked to an external packed library that is not part of this project.  I resolved that an committed the minor change to now include the local file it needed in the project directly.  If you redownload it, it should work fine for you.

**Comment by SimonRPSM** [comment]
Good stuff - thanks for the super quick fix!

I will give it another try then.
