### ISSUE TITLE
Cell Change event not fired when clicking out of control.

### ISSUE THREAD

**Issue by samsharp99** [unipsycho/LabVIEWdotNetDataGrid#30]
I have a DataGrid with a boolean checkbox column but the CellChange event and data update does not occur on clicking the checkbox, only once you click out of it onto another cell within the data grid. This means that the displayed values for the boolean columns does not always match the underlying data (if you do not select another cell first before reading the data).

Steps to reproduce:
1. Create a datagrid, populate with data with an event case for the 'CellValue Changed' event
2. Click into a cell and change the value
3. Click out of the datagrid (e.g. clicking on the front panel / another control)

The CellValue Changed event is not fired, and reading the grid data shows the previous value for the cell changed in Step 2.

Expected behaviour is that the event is fired when the control loses focus.

**Comment by picklecolor2** [comment]
My fix for Issue #18 will also address this issue. It adds an event handler for when the checkbox or combobox changes value and it commits the modification as a value change.
