### ISSUE TITLE
Write AllowUserToDeleteRows.vi uses the wrong property

### ISSUE THREAD

**Issue by picklecolor2** [unipsycho/LabVIEWdotNetDataGrid#32]
DataGridView.lvclass:AllowUserToDeleteRows.vi writes to the AllowUserToAddRows property of the DataGridView object. Should write to the AllowUserToDeleteRows property.
![image](https://user-images.githubusercontent.com/29785823/31097980-6c63d762-a77e-11e7-89e3-5fd93325bdef.png)

**Comment by unipsycho** [comment]
thanks, I've resolved this as well,
