### ISSUE TITLE
When binding data, AllowUserToAddRows needs propagated to the binding creation.

### ISSUE THREAD

**Issue by picklecolor2** [unipsycho/LabVIEWdotNetDataGrid#33]
As documented [here](http://www.bilgisayarmuhendisleri.com/DataGridView_csharp.htm), not only does the DataGridView need the option written to allow new row creation, when binding to a DataTable the BindingSource also need the AllowNew option set to match. Unless both are true the new row option isn't displayed. Proposed update to Set Data Binding.vi:
![image](https://user-images.githubusercontent.com/29785823/31098205-1a7d8348-a77f-11e7-84e7-945b301735f8.png)

**Comment by unipsycho** [comment]
great find, thanks for this tip, I've just commited the change.
