### ISSUE TITLE
Large number of reference leaks

### ISSUE THREAD

**Issue by JamesWiresmith** [unipsycho/LabVIEWdotNetDataGrid#39]
In debugging stability issues I've noticed there are a large number of references leaked by the datagridview.

A quick test shows that child references can be closed without causing problems with the parent (since .net will recognise it is still in use - see https://forums.ni.com/t5/LabVIEW/NET-Explicitly-closing-references-for-each-property-invoke-node/td-p/3688157) therefore these should be closed explicitly.

**Comment by unipsycho** [comment]
thanks for the commit to help resolve that! I've not had much time for this lately, glad you are making use of it as well though.

**Comment by JamesWiresmith** [comment]
No problem - I hope to have a pull request for you later today with all the changes in.
