### ISSUE TITLE
Right-click menu

### ISSUE THREAD

**Issue by smXplorer** [unipsycho/LabVIEWdotNetDataGrid#6]
The new caption feature is working fine, thanks.
One thing that is markedly different from the LabVIEW table object is the absence of a right-click menu. It would probably be expected by users that they could have a minimum of interaction with the data grid.
Of course you can already select and copy (but that doesn't appear as a right-click menu), but it could be useful to justify the text, or insert/delete columns/rows, etc.
Is this an implementation (lack of) feature or is the ActiveX object lacking this kind of ability?

**Comment by unipsycho** [comment]
Another great idea to add to the future list.  I'm going to close it from the issue list though and add it to the future todo items.  It would be great if someone else wants to pick up building an appropriate context menu as its implemented as a separate .net entity passed in as a property to the gridview.  Simple to do, but as usual, a context menu needs to have a number of configurable options (like allow insert, delete, edit) and be content aware potentially, so lots of things to think about to do it right.  That is why it isn't simply a turn on and off feature like in LabVIEW.  I usually end up disabling labview's at customer requests and implementing my own custom right click menus anyway so they are more intelligent and user friendly.
